# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=120)),
                ('origem', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('tombo', models.CharField(blank=True, max_length=300)),
                ('situacao', models.CharField(blank=True, max_length=120)),
                ('servidor', models.CharField(blank=True, max_length=120)),
                ('proprietario', models.CharField(blank=True, max_length=120)),
                ('local', models.CharField(blank=True, max_length=300)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Tipo'),
        ),
    ]
