# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='marca',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
