# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_auto_20160927_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cpf',
            field=models.CharField(max_length=16),
        ),
    ]
