# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0004_auto_20160927_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='lotado',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='whatsapp',
        ),
    ]
