# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0005_auto_20160928_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='adress',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registro',
            name='bairro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registro',
            name='cargo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registro',
            name='cep',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='registro',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registro',
            name='complemento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registro',
            name='lotado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registro',
            name='setor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nome',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
