# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0013_auto_20161108_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(default='Defaul', max_length=120),
        ),
    ]
