# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0016_item_movimentacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teste.Item'),
        ),
        migrations.AddField(
            model_name='tipo',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teste.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='patrimonio',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='modelo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
