# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.TextField()),
                ('dataN', models.DateField()),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
                ('bairro', models.CharField(max_length=120)),
                ('adress', models.CharField(max_length=120)),
                ('cep', models.IntegerField()),
                ('complemento', models.CharField(max_length=120)),
                ('lotado', models.CharField(max_length=120)),
                ('setor', models.CharField(max_length=120)),
                ('cargo', models.CharField(max_length=120)),
                ('telefone', models.IntegerField()),
                ('whatsapp', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
