# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cep',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registro',
            name='whatsapp',
            field=models.CharField(max_length=15),
        ),
    ]
