# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20160928_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='registro',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='registro',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
