# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0008_auto_20160928_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrar', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='user',
        ),
        migrations.AddField(
            model_name='grupo',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Registro'),
        ),
    ]
