# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20161107_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nome',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
