# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_grupo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(default='Defaut', max_length=120),
        ),
    ]
