# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20161108_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
