# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20161108_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('patrimonio', models.CharField(blank=True, max_length=120)),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('tombo', models.CharField(blank=True, max_length=300)),
                ('situacao', models.CharField(blank=True, max_length=120)),
                ('servidor', models.CharField(blank=True, max_length=120)),
                ('proprietario', models.CharField(blank=True, max_length=120)),
                ('local', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
