# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0019_auto_20161120_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='item',
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Tipo'),
        ),
    ]
