# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0023_auto_20161122_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teste.Item'),
        ),
    ]
