# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_tarefas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
    ]
