# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_remove_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='grupo',
            field=models.CharField(blank=True, max_length=26),
        ),
    ]
