# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20161201_0338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Cadastro',
        ),
    ]
