# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_auto_20161201_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='nfuncional',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
